[package]
name = "rust-lua-doc"
version = "0.1.0"
authors = ["Soviet Kitsune <SovietKitsune@soviet.solutions>"]
edition = "2018"

[dependencies]
rslua = "0.2.6"
pest = "2"
pest_derive = "2"
nom = "6"
